# Generated by Django 5.2.4 on 2025-07-26 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
